sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t cofeecoder/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true cofeecoder/react-test npm test

after_success:
  - docker build -t cofeecoder/multi-client ./client
  - docker build -t cofeecoder/multi-nginx ./nginx
  - docker build -t cofeecoder/multi-server ./server
  - docker build -t cofeecoder/multi-worker ./worker
  # Log in to the docker CLI
  - echo "PasswdAZN20!$" | docker login -u "cofeecoder" --password-stdin
  # Take those images and push them to docker hub
  - docker push cofeecoder/multi-client
  - docker push cofeecoder/multi-nginx
  - docker push cofeecoder/multi-server
  - docker push cofeecoder/multi-worker
